truncate table
  public.audit_logs,
  public.returns,
  public.shipping_records,
  public.invoices,
  public.receipts,
  public.payment_logs,
  public.payments,
  public.order_timeline,
  public.order_notes,
  public.order_items,
  public.orders,
  public.inventory_movements,
  public.product_images,
  public.products,
  public.reviews,
  public.testimonials,
  public.blog_posts,
  public.blog_categories,
  public.bookings,
  public.contact_inquiries,
  public.newsletter_subscribers,
  public.cart_items,
  public.addresses,
  public.brands,
  public.categories
restart identity cascade;
